# Generated by Django 2.1.2 on 2018-10-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('Raza', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='albums/imagen/')),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
