# Generated by Django 2.1.2 on 2018-10-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWeb', '0002_formulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
