# Generated by Django 2.1.2 on 2018-10-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWeb', '0003_auto_20181025_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='image',
            field=models.ImageField(default='SOME STRING', upload_to='albums'),
        ),
    ]
